# Generated by Django 5.1.4 on 2026-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture', models.URLField(blank=True)),
                ('skills', models.TextField(help_text='Separate skills with comma')),
            ],
        ),
    ]
